// <auto-generated />
using System;
using ConsultationBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsultationBackend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsultationBackend.Models.Relational.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EmailConfirmationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatId")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DocId");

                    b.HasIndex("PatId");

                    b.HasIndex("AppointmentDate", "AppointmentTime");

                    b.ToTable("appointments", (string)null);

                    b.HasData(
                        new
                        {
                            AppointmentId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AppointmentDate = new DateOnly(2026, 1, 15),
                            AppointmentStatus = "Confirmed",
                            AppointmentTime = new TimeOnly(9, 0, 0),
                            CreatedAt = new DateTime(2026, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmailConfirmationSent = false,
                            PatId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            AppointmentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AppointmentDate = new DateOnly(2026, 1, 16),
                            AppointmentStatus = "Completed",
                            AppointmentTime = new TimeOnly(10, 30, 0),
                            CreatedAt = new DateTime(2026, 1, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EmailConfirmationSent = true,
                            EmailSentAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            PatId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("ConsultationBackend.Models.Relational.Doctor", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("DocId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("doctors", (string)null);

                    b.HasData(
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "alice.carter@example.com",
                            Name = "Dr. Alice Carter"
                        },
                        new
                        {
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "ben.ortiz@example.com",
                            Name = "Dr. Ben Ortiz"
                        });
                });

            modelBuilder.Entity("ConsultationBackend.Models.Relational.Patient", b =>
                {
                    b.Property<Guid>("PatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("PatId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("patients", (string)null);

                    b.HasData(
                        new
                        {
                            PatId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Email = "john.doe@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            PatId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("ConsultationBackend.Models.Relational.Appointment", b =>
                {
                    b.HasOne("ConsultationBackend.Models.Relational.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsultationBackend.Models.Relational.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ConsultationBackend.Models.Relational.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ConsultationBackend.Models.Relational.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
