/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * ConsultationBackend
 * OpenAPI spec version: 1.0
 */

export interface BookingRequest {
  bookingId?: string;
  doctorId?: string;
  /** @nullable */
  doctorName?: string | null;
  patientId?: string;
  /** @nullable */
  patientName?: string | null;
  /** @nullable */
  patientEmail?: string | null;
}
