/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * BookingBackend
 * OpenAPI spec version: 1.0
 */
import type { AvailabilitySlot } from './availabilitySlot';

export interface DoctorAvailability {
  docId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  availabilitySlots?: AvailabilitySlot[] | null;
}
