/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * ConsultationBackend
 * OpenAPI spec version: 1.0
 */

export * from './bookingRequest';
export * from './getApiConsultationGetConsultationParams';
export * from './getApiConsultationGetDoctorAppointmentsParams';
export * from './getApiPrescriptionGetPrescriptionParams';
export * from './getApiSummaryGetSummaryParams';
export * from './getApiTranscriptGetTranscriptParams';
export * from './postApiPrescriptionApprovePrescriptionParams';
export * from './postApiPrescriptionGeneratePrescriptionParams';
export * from './postApiSummaryGenerateSummaryParams';
export * from './postApiTranscriptGenerateTranscriptBody';
export * from './postApiTranscriptGenerateTranscriptParams';
export * from './prescriptionEditRequest';
export * from './putApiPrescriptionEditPrescriptionParams';
export * from './putApiSummaryEditSumamryParams';
export * from './summaryEditRequest';
