// <auto-generated />
using System;
using BookingBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingBackend.Data.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260516120001_SeedBenSchedule")]
    partial class SeedBenSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingBackend.Models.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AppointmentStatus");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatId");

                    b.HasIndex("DocId", "AppointmentDate", "AppointmentTime")
                        .IsUnique();

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("BookingBackend.Models.Doctor", b =>
                {
                    b.Property<Guid>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocId");

                    b.ToTable("doctors", (string)null);
                });

            modelBuilder.Entity("BookingBackend.Models.Patient", b =>
                {
                    b.Property<Guid>("PatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatId");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("BookingBackend.Models.WorksOn", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfTheWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndsAt")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartsFrom")
                        .HasColumnType("time without time zone");

                    b.HasKey("DocId", "DayOfTheWeek");

                    b.ToTable("workson", (string)null);

                    b.HasData(
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfTheWeek = 0,
                            EndsAt = new TimeOnly(23, 59, 0),
                            StartsFrom = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfTheWeek = 1,
                            EndsAt = new TimeOnly(23, 59, 0),
                            StartsFrom = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfTheWeek = 2,
                            EndsAt = new TimeOnly(23, 59, 0),
                            StartsFrom = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfTheWeek = 3,
                            EndsAt = new TimeOnly(23, 59, 0),
                            StartsFrom = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfTheWeek = 4,
                            EndsAt = new TimeOnly(23, 59, 0),
                            StartsFrom = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfTheWeek = 5,
                            EndsAt = new TimeOnly(23, 59, 0),
                            StartsFrom = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("11111111-1111-1111-1111-111111111111"),
                            DayOfTheWeek = 6,
                            EndsAt = new TimeOnly(23, 59, 0),
                            StartsFrom = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DayOfTheWeek = 1,
                            EndsAt = new TimeOnly(17, 0, 0),
                            StartsFrom = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DayOfTheWeek = 2,
                            EndsAt = new TimeOnly(17, 0, 0),
                            StartsFrom = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DayOfTheWeek = 3,
                            EndsAt = new TimeOnly(17, 0, 0),
                            StartsFrom = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DayOfTheWeek = 4,
                            EndsAt = new TimeOnly(17, 0, 0),
                            StartsFrom = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DayOfTheWeek = 5,
                            EndsAt = new TimeOnly(17, 0, 0),
                            StartsFrom = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            DocId = new Guid("22222222-2222-2222-2222-222222222222"),
                            DayOfTheWeek = 6,
                            EndsAt = new TimeOnly(17, 0, 0),
                            StartsFrom = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("BookingBackend.Models.Appointment", b =>
                {
                    b.HasOne("BookingBackend.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookingBackend.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BookingBackend.Models.WorksOn", b =>
                {
                    b.HasOne("BookingBackend.Models.Doctor", "Doctor")
                        .WithMany("WorksOn")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("BookingBackend.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("WorksOn");
                });

            modelBuilder.Entity("BookingBackend.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
