/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * BookingBackend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppointmentDTO,
  CreateAppointmentDTO,
  DoctorAvailability
} from './model';

import { customFetch } from './customFetch';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postApiAppointmentResponse200TextPlain = {
  data: AppointmentDTO
  status: 200
}

export type postApiAppointmentResponse200ApplicationJson = {
  data: AppointmentDTO
  status: 200
}

export type postApiAppointmentResponse200TextJson = {
  data: AppointmentDTO
  status: 200
}

export type postApiAppointmentResponseSuccess = (postApiAppointmentResponse200TextPlain | postApiAppointmentResponse200ApplicationJson | postApiAppointmentResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiAppointmentResponse = (postApiAppointmentResponseSuccess)

export const getPostApiAppointmentUrl = () => {




  return `http://localhost:5050/api/Appointment`
}

export const postApiAppointment = async (createAppointmentDTO?: CreateAppointmentDTO, options?: RequestInit): Promise<postApiAppointmentResponse> => {

  return customFetch<postApiAppointmentResponse>(getPostApiAppointmentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAppointmentDTO,)
  }
);}




export const getPostApiAppointmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAppointment>>, TError,{data?: CreateAppointmentDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAppointment>>, TError,{data?: CreateAppointmentDTO}, TContext> => {

const mutationKey = ['postApiAppointment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAppointment>>, {data?: CreateAppointmentDTO}> = (props) => {
          const {data} = props ?? {};

          return  postApiAppointment(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAppointmentMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAppointment>>>
    export type PostApiAppointmentMutationBody = CreateAppointmentDTO | undefined
    export type PostApiAppointmentMutationError = unknown

    export const usePostApiAppointment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAppointment>>, TError,{data?: CreateAppointmentDTO}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAppointment>>,
        TError,
        {data?: CreateAppointmentDTO},
        TContext
      > => {
      return useMutation(getPostApiAppointmentMutationOptions(options), queryClient);
    }

export type getApiAppointmentResponse200TextPlain = {
  data: AppointmentDTO[]
  status: 200
}

export type getApiAppointmentResponse200ApplicationJson = {
  data: AppointmentDTO[]
  status: 200
}

export type getApiAppointmentResponse200TextJson = {
  data: AppointmentDTO[]
  status: 200
}

export type getApiAppointmentResponseSuccess = (getApiAppointmentResponse200TextPlain | getApiAppointmentResponse200ApplicationJson | getApiAppointmentResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiAppointmentResponse = (getApiAppointmentResponseSuccess)

export const getGetApiAppointmentUrl = () => {




  return `http://localhost:5050/api/Appointment`
}

export const getApiAppointment = async ( options?: RequestInit): Promise<getApiAppointmentResponse> => {

  return customFetch<getApiAppointmentResponse>(getGetApiAppointmentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAppointmentQueryKey = () => {
    return [
    `http://localhost:5050/api/Appointment`
    ] as const;
    }


export const getGetApiAppointmentQueryOptions = <TData = Awaited<ReturnType<typeof getApiAppointment>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAppointmentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAppointment>>> = ({ signal }) => getApiAppointment({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAppointmentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAppointment>>>
export type GetApiAppointmentQueryError = unknown


export function useGetApiAppointment<TData = Awaited<ReturnType<typeof getApiAppointment>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAppointment>>,
          TError,
          Awaited<ReturnType<typeof getApiAppointment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAppointment<TData = Awaited<ReturnType<typeof getApiAppointment>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAppointment>>,
          TError,
          Awaited<ReturnType<typeof getApiAppointment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAppointment<TData = Awaited<ReturnType<typeof getApiAppointment>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAppointment<TData = Awaited<ReturnType<typeof getApiAppointment>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAppointmentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getApiAvailabilityDoctorsResponse200TextPlain = {
  data: DoctorAvailability[]
  status: 200
}

export type getApiAvailabilityDoctorsResponse200ApplicationJson = {
  data: DoctorAvailability[]
  status: 200
}

export type getApiAvailabilityDoctorsResponse200TextJson = {
  data: DoctorAvailability[]
  status: 200
}

export type getApiAvailabilityDoctorsResponseSuccess = (getApiAvailabilityDoctorsResponse200TextPlain | getApiAvailabilityDoctorsResponse200ApplicationJson | getApiAvailabilityDoctorsResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiAvailabilityDoctorsResponse = (getApiAvailabilityDoctorsResponseSuccess)

export const getGetApiAvailabilityDoctorsUrl = () => {




  return `http://localhost:5050/api/Availability/doctors`
}

export const getApiAvailabilityDoctors = async ( options?: RequestInit): Promise<getApiAvailabilityDoctorsResponse> => {

  return customFetch<getApiAvailabilityDoctorsResponse>(getGetApiAvailabilityDoctorsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAvailabilityDoctorsQueryKey = () => {
    return [
    `http://localhost:5050/api/Availability/doctors`
    ] as const;
    }


export const getGetApiAvailabilityDoctorsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAvailabilityDoctorsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>> = ({ signal }) => getApiAvailabilityDoctors({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAvailabilityDoctorsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>>
export type GetApiAvailabilityDoctorsQueryError = unknown


export function useGetApiAvailabilityDoctors<TData = Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAvailabilityDoctors>>,
          TError,
          Awaited<ReturnType<typeof getApiAvailabilityDoctors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAvailabilityDoctors<TData = Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAvailabilityDoctors>>,
          TError,
          Awaited<ReturnType<typeof getApiAvailabilityDoctors>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAvailabilityDoctors<TData = Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAvailabilityDoctors<TData = Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAvailabilityDoctorsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getPublicResponse200 = {
  data: void
  status: 200
}

export type getPublicResponseSuccess = (getPublicResponse200) & {
  headers: Headers;
};
;

export type getPublicResponse = (getPublicResponseSuccess)

export const getGetPublicUrl = () => {




  return `http://localhost:5050/api/public`
}

export const getPublic = async ( options?: RequestInit): Promise<getPublicResponse> => {

  return customFetch<getPublicResponse>(getGetPublicUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPublicQueryKey = () => {
    return [
    `http://localhost:5050/api/public`
    ] as const;
    }


export const getGetPublicQueryOptions = <TData = Awaited<ReturnType<typeof getPublic>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublic>>> = ({ signal }) => getPublic({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPublicQueryResult = NonNullable<Awaited<ReturnType<typeof getPublic>>>
export type GetPublicQueryError = unknown


export function useGetPublic<TData = Awaited<ReturnType<typeof getPublic>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublic>>,
          TError,
          Awaited<ReturnType<typeof getPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublic<TData = Awaited<ReturnType<typeof getPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublic>>,
          TError,
          Awaited<ReturnType<typeof getPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublic<TData = Awaited<ReturnType<typeof getPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPublic<TData = Awaited<ReturnType<typeof getPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPublicQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getPrivateResponse200 = {
  data: void
  status: 200
}

export type getPrivateResponseSuccess = (getPrivateResponse200) & {
  headers: Headers;
};
;

export type getPrivateResponse = (getPrivateResponseSuccess)

export const getGetPrivateUrl = () => {




  return `http://localhost:5050/api/private`
}

export const getPrivate = async ( options?: RequestInit): Promise<getPrivateResponse> => {

  return customFetch<getPrivateResponse>(getGetPrivateUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPrivateQueryKey = () => {
    return [
    `http://localhost:5050/api/private`
    ] as const;
    }


export const getGetPrivateQueryOptions = <TData = Awaited<ReturnType<typeof getPrivate>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrivateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrivate>>> = ({ signal }) => getPrivate({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPrivateQueryResult = NonNullable<Awaited<ReturnType<typeof getPrivate>>>
export type GetPrivateQueryError = unknown


export function useGetPrivate<TData = Awaited<ReturnType<typeof getPrivate>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrivate>>,
          TError,
          Awaited<ReturnType<typeof getPrivate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrivate<TData = Awaited<ReturnType<typeof getPrivate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrivate>>,
          TError,
          Awaited<ReturnType<typeof getPrivate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrivate<TData = Awaited<ReturnType<typeof getPrivate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPrivate<TData = Awaited<ReturnType<typeof getPrivate>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPrivateQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
