/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * BookingBackend
 * OpenAPI spec version: 1.0
 */

export interface AppointmentDTO {
  appointmentId?: string;
  docId?: string;
  patId?: string;
  appointmentDate?: string;
  appointmentTime?: string;
  /** @nullable */
  status?: string | null;
  createdAt?: string;
}
