/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * BookingBackend
 * OpenAPI spec version: 1.0
 */

export interface AvailabilitySlot {
  dayOfTheWeek?: number;
  startsFrom?: string;
  endsAt?: string;
}
