/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * BookingBackend
 * OpenAPI spec version: 1.0
 */

export * from './appointmentDTO';
export * from './availabilitySlot';
export * from './createAppointmentDTO';
export * from './doctorAvailability';
