/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * ConsultationBackend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BookingRequest,
  GetApiConsultationGetConsultationParams,
  GetApiPrescriptionGetPrescriptionParams,
  GetApiSummaryGetSummaryParams,
  GetApiTranscriptGetTranscriptParams,
  PostApiPrescriptionApprovePrescriptionParams,
  PostApiPrescriptionGeneratePrescriptionParams,
  PostApiSummaryGenerateSummaryParams,
  PostApiTranscriptGenerateTranscriptBody,
  PostApiTranscriptGenerateTranscriptParams,
  PrescriptionEditRequest,
  PutApiPrescriptionEditPrescriptionParams,
  PutApiSummaryEditSumamryParams,
  SummaryEditRequest
} from './model';

export type postApiConsultationStartConsultationResponse200 = {
  data: void
  status: 200
}

export type postApiConsultationStartConsultationResponseSuccess = (postApiConsultationStartConsultationResponse200) & {
  headers: Headers;
};
;

export type postApiConsultationStartConsultationResponse = (postApiConsultationStartConsultationResponseSuccess)

export const getPostApiConsultationStartConsultationUrl = () => {




  return `/api/Consultation/StartConsultation`
}

export const postApiConsultationStartConsultation = async (bookingRequest: BookingRequest, options?: RequestInit): Promise<postApiConsultationStartConsultationResponse> => {

  const res = await fetch(getPostApiConsultationStartConsultationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bookingRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiConsultationStartConsultationResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiConsultationStartConsultationResponse
}




export const getPostApiConsultationStartConsultationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiConsultationStartConsultation>>, TError,{data: BookingRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiConsultationStartConsultation>>, TError,{data: BookingRequest}, TContext> => {

const mutationKey = ['postApiConsultationStartConsultation'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiConsultationStartConsultation>>, {data: BookingRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiConsultationStartConsultation(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiConsultationStartConsultationMutationResult = NonNullable<Awaited<ReturnType<typeof postApiConsultationStartConsultation>>>
    export type PostApiConsultationStartConsultationMutationBody = BookingRequest
    export type PostApiConsultationStartConsultationMutationError = unknown

    export const usePostApiConsultationStartConsultation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiConsultationStartConsultation>>, TError,{data: BookingRequest}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiConsultationStartConsultation>>,
        TError,
        {data: BookingRequest},
        TContext
      > => {
      return useMutation(getPostApiConsultationStartConsultationMutationOptions(options));
    }

export type getApiConsultationGetConsultationResponse200 = {
  data: void
  status: 200
}

export type getApiConsultationGetConsultationResponseSuccess = (getApiConsultationGetConsultationResponse200) & {
  headers: Headers;
};
;

export type getApiConsultationGetConsultationResponse = (getApiConsultationGetConsultationResponseSuccess)

export const getGetApiConsultationGetConsultationUrl = (params?: GetApiConsultationGetConsultationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Consultation/GetConsultation?${stringifiedParams}` : `/api/Consultation/GetConsultation`
}

export const getApiConsultationGetConsultation = async (params?: GetApiConsultationGetConsultationParams, options?: RequestInit): Promise<getApiConsultationGetConsultationResponse> => {

  const res = await fetch(getGetApiConsultationGetConsultationUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiConsultationGetConsultationResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiConsultationGetConsultationResponse
}





export const getGetApiConsultationGetConsultationQueryKey = (params?: GetApiConsultationGetConsultationParams,) => {
    return [
    `/api/Consultation/GetConsultation`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiConsultationGetConsultationQueryOptions = <TData = Awaited<ReturnType<typeof getApiConsultationGetConsultation>>, TError = unknown>(params?: GetApiConsultationGetConsultationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiConsultationGetConsultation>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiConsultationGetConsultationQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiConsultationGetConsultation>>> = ({ signal }) => getApiConsultationGetConsultation(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiConsultationGetConsultation>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiConsultationGetConsultationQueryResult = NonNullable<Awaited<ReturnType<typeof getApiConsultationGetConsultation>>>
export type GetApiConsultationGetConsultationQueryError = unknown



export function useGetApiConsultationGetConsultation<TData = Awaited<ReturnType<typeof getApiConsultationGetConsultation>>, TError = unknown>(
 params?: GetApiConsultationGetConsultationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiConsultationGetConsultation>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiConsultationGetConsultationQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type postApiPrescriptionGeneratePrescriptionResponse200 = {
  data: void
  status: 200
}

export type postApiPrescriptionGeneratePrescriptionResponseSuccess = (postApiPrescriptionGeneratePrescriptionResponse200) & {
  headers: Headers;
};
;

export type postApiPrescriptionGeneratePrescriptionResponse = (postApiPrescriptionGeneratePrescriptionResponseSuccess)

export const getPostApiPrescriptionGeneratePrescriptionUrl = (params?: PostApiPrescriptionGeneratePrescriptionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Prescription/GeneratePrescription?${stringifiedParams}` : `/api/Prescription/GeneratePrescription`
}

export const postApiPrescriptionGeneratePrescription = async (params?: PostApiPrescriptionGeneratePrescriptionParams, options?: RequestInit): Promise<postApiPrescriptionGeneratePrescriptionResponse> => {

  const res = await fetch(getPostApiPrescriptionGeneratePrescriptionUrl(params),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiPrescriptionGeneratePrescriptionResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiPrescriptionGeneratePrescriptionResponse
}




export const getPostApiPrescriptionGeneratePrescriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPrescriptionGeneratePrescription>>, TError,{params?: PostApiPrescriptionGeneratePrescriptionParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPrescriptionGeneratePrescription>>, TError,{params?: PostApiPrescriptionGeneratePrescriptionParams}, TContext> => {

const mutationKey = ['postApiPrescriptionGeneratePrescription'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPrescriptionGeneratePrescription>>, {params?: PostApiPrescriptionGeneratePrescriptionParams}> = (props) => {
          const {params} = props ?? {};

          return  postApiPrescriptionGeneratePrescription(params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPrescriptionGeneratePrescriptionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPrescriptionGeneratePrescription>>>

    export type PostApiPrescriptionGeneratePrescriptionMutationError = unknown

    export const usePostApiPrescriptionGeneratePrescription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPrescriptionGeneratePrescription>>, TError,{params?: PostApiPrescriptionGeneratePrescriptionParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiPrescriptionGeneratePrescription>>,
        TError,
        {params?: PostApiPrescriptionGeneratePrescriptionParams},
        TContext
      > => {
      return useMutation(getPostApiPrescriptionGeneratePrescriptionMutationOptions(options));
    }

export type getApiPrescriptionGetPrescriptionResponse200 = {
  data: void
  status: 200
}

export type getApiPrescriptionGetPrescriptionResponseSuccess = (getApiPrescriptionGetPrescriptionResponse200) & {
  headers: Headers;
};
;

export type getApiPrescriptionGetPrescriptionResponse = (getApiPrescriptionGetPrescriptionResponseSuccess)

export const getGetApiPrescriptionGetPrescriptionUrl = (params?: GetApiPrescriptionGetPrescriptionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Prescription/GetPrescription?${stringifiedParams}` : `/api/Prescription/GetPrescription`
}

export const getApiPrescriptionGetPrescription = async (params?: GetApiPrescriptionGetPrescriptionParams, options?: RequestInit): Promise<getApiPrescriptionGetPrescriptionResponse> => {

  const res = await fetch(getGetApiPrescriptionGetPrescriptionUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiPrescriptionGetPrescriptionResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiPrescriptionGetPrescriptionResponse
}





export const getGetApiPrescriptionGetPrescriptionQueryKey = (params?: GetApiPrescriptionGetPrescriptionParams,) => {
    return [
    `/api/Prescription/GetPrescription`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiPrescriptionGetPrescriptionQueryOptions = <TData = Awaited<ReturnType<typeof getApiPrescriptionGetPrescription>>, TError = unknown>(params?: GetApiPrescriptionGetPrescriptionParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiPrescriptionGetPrescription>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPrescriptionGetPrescriptionQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPrescriptionGetPrescription>>> = ({ signal }) => getApiPrescriptionGetPrescription(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPrescriptionGetPrescription>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiPrescriptionGetPrescriptionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPrescriptionGetPrescription>>>
export type GetApiPrescriptionGetPrescriptionQueryError = unknown



export function useGetApiPrescriptionGetPrescription<TData = Awaited<ReturnType<typeof getApiPrescriptionGetPrescription>>, TError = unknown>(
 params?: GetApiPrescriptionGetPrescriptionParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiPrescriptionGetPrescription>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiPrescriptionGetPrescriptionQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type putApiPrescriptionEditPrescriptionResponse200 = {
  data: void
  status: 200
}

export type putApiPrescriptionEditPrescriptionResponseSuccess = (putApiPrescriptionEditPrescriptionResponse200) & {
  headers: Headers;
};
;

export type putApiPrescriptionEditPrescriptionResponse = (putApiPrescriptionEditPrescriptionResponseSuccess)

export const getPutApiPrescriptionEditPrescriptionUrl = (params?: PutApiPrescriptionEditPrescriptionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Prescription/EditPrescription?${stringifiedParams}` : `/api/Prescription/EditPrescription`
}

export const putApiPrescriptionEditPrescription = async (prescriptionEditRequest: PrescriptionEditRequest,
    params?: PutApiPrescriptionEditPrescriptionParams, options?: RequestInit): Promise<putApiPrescriptionEditPrescriptionResponse> => {

  const res = await fetch(getPutApiPrescriptionEditPrescriptionUrl(params),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      prescriptionEditRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiPrescriptionEditPrescriptionResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiPrescriptionEditPrescriptionResponse
}




export const getPutApiPrescriptionEditPrescriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPrescriptionEditPrescription>>, TError,{data: PrescriptionEditRequest;params?: PutApiPrescriptionEditPrescriptionParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiPrescriptionEditPrescription>>, TError,{data: PrescriptionEditRequest;params?: PutApiPrescriptionEditPrescriptionParams}, TContext> => {

const mutationKey = ['putApiPrescriptionEditPrescription'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiPrescriptionEditPrescription>>, {data: PrescriptionEditRequest;params?: PutApiPrescriptionEditPrescriptionParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putApiPrescriptionEditPrescription(data,params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiPrescriptionEditPrescriptionMutationResult = NonNullable<Awaited<ReturnType<typeof putApiPrescriptionEditPrescription>>>
    export type PutApiPrescriptionEditPrescriptionMutationBody = PrescriptionEditRequest
    export type PutApiPrescriptionEditPrescriptionMutationError = unknown

    export const usePutApiPrescriptionEditPrescription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPrescriptionEditPrescription>>, TError,{data: PrescriptionEditRequest;params?: PutApiPrescriptionEditPrescriptionParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putApiPrescriptionEditPrescription>>,
        TError,
        {data: PrescriptionEditRequest;params?: PutApiPrescriptionEditPrescriptionParams},
        TContext
      > => {
      return useMutation(getPutApiPrescriptionEditPrescriptionMutationOptions(options));
    }

export type postApiPrescriptionApprovePrescriptionResponse200 = {
  data: void
  status: 200
}

export type postApiPrescriptionApprovePrescriptionResponseSuccess = (postApiPrescriptionApprovePrescriptionResponse200) & {
  headers: Headers;
};
;

export type postApiPrescriptionApprovePrescriptionResponse = (postApiPrescriptionApprovePrescriptionResponseSuccess)

export const getPostApiPrescriptionApprovePrescriptionUrl = (params?: PostApiPrescriptionApprovePrescriptionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Prescription/ApprovePrescription?${stringifiedParams}` : `/api/Prescription/ApprovePrescription`
}

export const postApiPrescriptionApprovePrescription = async (params?: PostApiPrescriptionApprovePrescriptionParams, options?: RequestInit): Promise<postApiPrescriptionApprovePrescriptionResponse> => {

  const res = await fetch(getPostApiPrescriptionApprovePrescriptionUrl(params),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiPrescriptionApprovePrescriptionResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiPrescriptionApprovePrescriptionResponse
}




export const getPostApiPrescriptionApprovePrescriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPrescriptionApprovePrescription>>, TError,{params?: PostApiPrescriptionApprovePrescriptionParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPrescriptionApprovePrescription>>, TError,{params?: PostApiPrescriptionApprovePrescriptionParams}, TContext> => {

const mutationKey = ['postApiPrescriptionApprovePrescription'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPrescriptionApprovePrescription>>, {params?: PostApiPrescriptionApprovePrescriptionParams}> = (props) => {
          const {params} = props ?? {};

          return  postApiPrescriptionApprovePrescription(params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPrescriptionApprovePrescriptionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPrescriptionApprovePrescription>>>

    export type PostApiPrescriptionApprovePrescriptionMutationError = unknown

    export const usePostApiPrescriptionApprovePrescription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPrescriptionApprovePrescription>>, TError,{params?: PostApiPrescriptionApprovePrescriptionParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiPrescriptionApprovePrescription>>,
        TError,
        {params?: PostApiPrescriptionApprovePrescriptionParams},
        TContext
      > => {
      return useMutation(getPostApiPrescriptionApprovePrescriptionMutationOptions(options));
    }

export type postApiSummaryGenerateSummaryResponse200 = {
  data: void
  status: 200
}

export type postApiSummaryGenerateSummaryResponseSuccess = (postApiSummaryGenerateSummaryResponse200) & {
  headers: Headers;
};
;

export type postApiSummaryGenerateSummaryResponse = (postApiSummaryGenerateSummaryResponseSuccess)

export const getPostApiSummaryGenerateSummaryUrl = (params?: PostApiSummaryGenerateSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Summary/GenerateSummary?${stringifiedParams}` : `/api/Summary/GenerateSummary`
}

export const postApiSummaryGenerateSummary = async (params?: PostApiSummaryGenerateSummaryParams, options?: RequestInit): Promise<postApiSummaryGenerateSummaryResponse> => {

  const res = await fetch(getPostApiSummaryGenerateSummaryUrl(params),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiSummaryGenerateSummaryResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiSummaryGenerateSummaryResponse
}




export const getPostApiSummaryGenerateSummaryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSummaryGenerateSummary>>, TError,{params?: PostApiSummaryGenerateSummaryParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSummaryGenerateSummary>>, TError,{params?: PostApiSummaryGenerateSummaryParams}, TContext> => {

const mutationKey = ['postApiSummaryGenerateSummary'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSummaryGenerateSummary>>, {params?: PostApiSummaryGenerateSummaryParams}> = (props) => {
          const {params} = props ?? {};

          return  postApiSummaryGenerateSummary(params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSummaryGenerateSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSummaryGenerateSummary>>>

    export type PostApiSummaryGenerateSummaryMutationError = unknown

    export const usePostApiSummaryGenerateSummary = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSummaryGenerateSummary>>, TError,{params?: PostApiSummaryGenerateSummaryParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiSummaryGenerateSummary>>,
        TError,
        {params?: PostApiSummaryGenerateSummaryParams},
        TContext
      > => {
      return useMutation(getPostApiSummaryGenerateSummaryMutationOptions(options));
    }

export type getApiSummaryGetSummaryResponse200 = {
  data: void
  status: 200
}

export type getApiSummaryGetSummaryResponseSuccess = (getApiSummaryGetSummaryResponse200) & {
  headers: Headers;
};
;

export type getApiSummaryGetSummaryResponse = (getApiSummaryGetSummaryResponseSuccess)

export const getGetApiSummaryGetSummaryUrl = (params?: GetApiSummaryGetSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Summary/GetSummary?${stringifiedParams}` : `/api/Summary/GetSummary`
}

export const getApiSummaryGetSummary = async (params?: GetApiSummaryGetSummaryParams, options?: RequestInit): Promise<getApiSummaryGetSummaryResponse> => {

  const res = await fetch(getGetApiSummaryGetSummaryUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiSummaryGetSummaryResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiSummaryGetSummaryResponse
}





export const getGetApiSummaryGetSummaryQueryKey = (params?: GetApiSummaryGetSummaryParams,) => {
    return [
    `/api/Summary/GetSummary`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiSummaryGetSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getApiSummaryGetSummary>>, TError = unknown>(params?: GetApiSummaryGetSummaryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiSummaryGetSummary>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSummaryGetSummaryQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSummaryGetSummary>>> = ({ signal }) => getApiSummaryGetSummary(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSummaryGetSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiSummaryGetSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSummaryGetSummary>>>
export type GetApiSummaryGetSummaryQueryError = unknown



export function useGetApiSummaryGetSummary<TData = Awaited<ReturnType<typeof getApiSummaryGetSummary>>, TError = unknown>(
 params?: GetApiSummaryGetSummaryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiSummaryGetSummary>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiSummaryGetSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type putApiSummaryEditSumamryResponse200 = {
  data: void
  status: 200
}

export type putApiSummaryEditSumamryResponseSuccess = (putApiSummaryEditSumamryResponse200) & {
  headers: Headers;
};
;

export type putApiSummaryEditSumamryResponse = (putApiSummaryEditSumamryResponseSuccess)

export const getPutApiSummaryEditSumamryUrl = (params?: PutApiSummaryEditSumamryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Summary/EditSumamry?${stringifiedParams}` : `/api/Summary/EditSumamry`
}

export const putApiSummaryEditSumamry = async (summaryEditRequest: SummaryEditRequest,
    params?: PutApiSummaryEditSumamryParams, options?: RequestInit): Promise<putApiSummaryEditSumamryResponse> => {

  const res = await fetch(getPutApiSummaryEditSumamryUrl(params),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      summaryEditRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putApiSummaryEditSumamryResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as putApiSummaryEditSumamryResponse
}




export const getPutApiSummaryEditSumamryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSummaryEditSumamry>>, TError,{data: SummaryEditRequest;params?: PutApiSummaryEditSumamryParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putApiSummaryEditSumamry>>, TError,{data: SummaryEditRequest;params?: PutApiSummaryEditSumamryParams}, TContext> => {

const mutationKey = ['putApiSummaryEditSumamry'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiSummaryEditSumamry>>, {data: SummaryEditRequest;params?: PutApiSummaryEditSumamryParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putApiSummaryEditSumamry(data,params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiSummaryEditSumamryMutationResult = NonNullable<Awaited<ReturnType<typeof putApiSummaryEditSumamry>>>
    export type PutApiSummaryEditSumamryMutationBody = SummaryEditRequest
    export type PutApiSummaryEditSumamryMutationError = unknown

    export const usePutApiSummaryEditSumamry = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiSummaryEditSumamry>>, TError,{data: SummaryEditRequest;params?: PutApiSummaryEditSumamryParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putApiSummaryEditSumamry>>,
        TError,
        {data: SummaryEditRequest;params?: PutApiSummaryEditSumamryParams},
        TContext
      > => {
      return useMutation(getPutApiSummaryEditSumamryMutationOptions(options));
    }

export type postApiTranscriptGenerateTranscriptResponse200 = {
  data: void
  status: 200
}

export type postApiTranscriptGenerateTranscriptResponseSuccess = (postApiTranscriptGenerateTranscriptResponse200) & {
  headers: Headers;
};
;

export type postApiTranscriptGenerateTranscriptResponse = (postApiTranscriptGenerateTranscriptResponseSuccess)

export const getPostApiTranscriptGenerateTranscriptUrl = (params?: PostApiTranscriptGenerateTranscriptParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Transcript/GenerateTranscript?${stringifiedParams}` : `/api/Transcript/GenerateTranscript`
}

export const postApiTranscriptGenerateTranscript = async (postApiTranscriptGenerateTranscriptBody: PostApiTranscriptGenerateTranscriptBody,
    params?: PostApiTranscriptGenerateTranscriptParams, options?: RequestInit): Promise<postApiTranscriptGenerateTranscriptResponse> => {
    const formData = new FormData();
if(postApiTranscriptGenerateTranscriptBody.audio !== undefined) {
 formData.append(`audio`, postApiTranscriptGenerateTranscriptBody.audio);
 }

  const res = await fetch(getPostApiTranscriptGenerateTranscriptUrl(params),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiTranscriptGenerateTranscriptResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiTranscriptGenerateTranscriptResponse
}




export const getPostApiTranscriptGenerateTranscriptMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTranscriptGenerateTranscript>>, TError,{data: PostApiTranscriptGenerateTranscriptBody;params?: PostApiTranscriptGenerateTranscriptParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTranscriptGenerateTranscript>>, TError,{data: PostApiTranscriptGenerateTranscriptBody;params?: PostApiTranscriptGenerateTranscriptParams}, TContext> => {

const mutationKey = ['postApiTranscriptGenerateTranscript'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTranscriptGenerateTranscript>>, {data: PostApiTranscriptGenerateTranscriptBody;params?: PostApiTranscriptGenerateTranscriptParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postApiTranscriptGenerateTranscript(data,params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTranscriptGenerateTranscriptMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTranscriptGenerateTranscript>>>
    export type PostApiTranscriptGenerateTranscriptMutationBody = PostApiTranscriptGenerateTranscriptBody
    export type PostApiTranscriptGenerateTranscriptMutationError = unknown

    export const usePostApiTranscriptGenerateTranscript = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTranscriptGenerateTranscript>>, TError,{data: PostApiTranscriptGenerateTranscriptBody;params?: PostApiTranscriptGenerateTranscriptParams}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiTranscriptGenerateTranscript>>,
        TError,
        {data: PostApiTranscriptGenerateTranscriptBody;params?: PostApiTranscriptGenerateTranscriptParams},
        TContext
      > => {
      return useMutation(getPostApiTranscriptGenerateTranscriptMutationOptions(options));
    }

export type getApiTranscriptGetTranscriptResponse200 = {
  data: void
  status: 200
}

export type getApiTranscriptGetTranscriptResponseSuccess = (getApiTranscriptGetTranscriptResponse200) & {
  headers: Headers;
};
;

export type getApiTranscriptGetTranscriptResponse = (getApiTranscriptGetTranscriptResponseSuccess)

export const getGetApiTranscriptGetTranscriptUrl = (params?: GetApiTranscriptGetTranscriptParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/Transcript/GetTranscript?${stringifiedParams}` : `/api/Transcript/GetTranscript`
}

export const getApiTranscriptGetTranscript = async (params?: GetApiTranscriptGetTranscriptParams, options?: RequestInit): Promise<getApiTranscriptGetTranscriptResponse> => {

  const res = await fetch(getGetApiTranscriptGetTranscriptUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiTranscriptGetTranscriptResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiTranscriptGetTranscriptResponse
}





export const getGetApiTranscriptGetTranscriptQueryKey = (params?: GetApiTranscriptGetTranscriptParams,) => {
    return [
    `/api/Transcript/GetTranscript`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiTranscriptGetTranscriptQueryOptions = <TData = Awaited<ReturnType<typeof getApiTranscriptGetTranscript>>, TError = unknown>(params?: GetApiTranscriptGetTranscriptParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiTranscriptGetTranscript>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTranscriptGetTranscriptQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTranscriptGetTranscript>>> = ({ signal }) => getApiTranscriptGetTranscript(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTranscriptGetTranscript>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiTranscriptGetTranscriptQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTranscriptGetTranscript>>>
export type GetApiTranscriptGetTranscriptQueryError = unknown



export function useGetApiTranscriptGetTranscript<TData = Awaited<ReturnType<typeof getApiTranscriptGetTranscript>>, TError = unknown>(
 params?: GetApiTranscriptGetTranscriptParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiTranscriptGetTranscript>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiTranscriptGetTranscriptQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
