/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * BookingBackend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppointmentDTO,
  CreateAppointmentDTO,
  DoctorAvailability
} from './model';

export type postApiAppointmentResponse200TextPlain = {
  data: AppointmentDTO
  status: 200
}

export type postApiAppointmentResponse200ApplicationJson = {
  data: AppointmentDTO
  status: 200
}

export type postApiAppointmentResponse200TextJson = {
  data: AppointmentDTO
  status: 200
}

export type postApiAppointmentResponseSuccess = (postApiAppointmentResponse200TextPlain | postApiAppointmentResponse200ApplicationJson | postApiAppointmentResponse200TextJson) & {
  headers: Headers;
};
;

export type postApiAppointmentResponse = (postApiAppointmentResponseSuccess)

export const getPostApiAppointmentUrl = () => {




  return `/api/Appointment`
}

export const postApiAppointment = async (createAppointmentDTO: CreateAppointmentDTO, options?: RequestInit): Promise<postApiAppointmentResponse> => {

  const res = await fetch(getPostApiAppointmentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createAppointmentDTO,)
  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAppointmentResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAppointmentResponse
}




export const getPostApiAppointmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAppointment>>, TError,{data: CreateAppointmentDTO}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAppointment>>, TError,{data: CreateAppointmentDTO}, TContext> => {

const mutationKey = ['postApiAppointment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAppointment>>, {data: CreateAppointmentDTO}> = (props) => {
          const {data} = props ?? {};

          return  postApiAppointment(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAppointmentMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAppointment>>>
    export type PostApiAppointmentMutationBody = CreateAppointmentDTO
    export type PostApiAppointmentMutationError = unknown

    export const usePostApiAppointment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAppointment>>, TError,{data: CreateAppointmentDTO}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postApiAppointment>>,
        TError,
        {data: CreateAppointmentDTO},
        TContext
      > => {
      return useMutation(getPostApiAppointmentMutationOptions(options));
    }

export type getApiAppointmentResponse200TextPlain = {
  data: AppointmentDTO[]
  status: 200
}

export type getApiAppointmentResponse200ApplicationJson = {
  data: AppointmentDTO[]
  status: 200
}

export type getApiAppointmentResponse200TextJson = {
  data: AppointmentDTO[]
  status: 200
}

export type getApiAppointmentResponseSuccess = (getApiAppointmentResponse200TextPlain | getApiAppointmentResponse200ApplicationJson | getApiAppointmentResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiAppointmentResponse = (getApiAppointmentResponseSuccess)

export const getGetApiAppointmentUrl = () => {




  return `/api/Appointment`
}

export const getApiAppointment = async ( options?: RequestInit): Promise<getApiAppointmentResponse> => {

  const res = await fetch(getGetApiAppointmentUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiAppointmentResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAppointmentResponse
}





export const getGetApiAppointmentQueryKey = () => {
    return [
    `/api/Appointment`
    ] as const;
    }


export const getGetApiAppointmentQueryOptions = <TData = Awaited<ReturnType<typeof getApiAppointment>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAppointmentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAppointment>>> = ({ signal }) => getApiAppointment({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAppointmentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAppointment>>>
export type GetApiAppointmentQueryError = unknown



export function useGetApiAppointment<TData = Awaited<ReturnType<typeof getApiAppointment>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAppointment>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAppointmentQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getApiAvailabilityDoctorsResponse200TextPlain = {
  data: DoctorAvailability[]
  status: 200
}

export type getApiAvailabilityDoctorsResponse200ApplicationJson = {
  data: DoctorAvailability[]
  status: 200
}

export type getApiAvailabilityDoctorsResponse200TextJson = {
  data: DoctorAvailability[]
  status: 200
}

export type getApiAvailabilityDoctorsResponseSuccess = (getApiAvailabilityDoctorsResponse200TextPlain | getApiAvailabilityDoctorsResponse200ApplicationJson | getApiAvailabilityDoctorsResponse200TextJson) & {
  headers: Headers;
};
;

export type getApiAvailabilityDoctorsResponse = (getApiAvailabilityDoctorsResponseSuccess)

export const getGetApiAvailabilityDoctorsUrl = () => {




  return `/api/Availability/doctors`
}

export const getApiAvailabilityDoctors = async ( options?: RequestInit): Promise<getApiAvailabilityDoctorsResponse> => {

  const res = await fetch(getGetApiAvailabilityDoctorsUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiAvailabilityDoctorsResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAvailabilityDoctorsResponse
}





export const getGetApiAvailabilityDoctorsQueryKey = () => {
    return [
    `/api/Availability/doctors`
    ] as const;
    }


export const getGetApiAvailabilityDoctorsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAvailabilityDoctorsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>> = ({ signal }) => getApiAvailabilityDoctors({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApiAvailabilityDoctorsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>>
export type GetApiAvailabilityDoctorsQueryError = unknown



export function useGetApiAvailabilityDoctors<TData = Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApiAvailabilityDoctors>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApiAvailabilityDoctorsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getPublicResponse200 = {
  data: void
  status: 200
}

export type getPublicResponseSuccess = (getPublicResponse200) & {
  headers: Headers;
};
;

export type getPublicResponse = (getPublicResponseSuccess)

export const getGetPublicUrl = () => {




  return `/api/public`
}

export const getPublic = async ( options?: RequestInit): Promise<getPublicResponse> => {

  const res = await fetch(getGetPublicUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPublicResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getPublicResponse
}





export const getGetPublicQueryKey = () => {
    return [
    `/api/public`
    ] as const;
    }


export const getGetPublicQueryOptions = <TData = Awaited<ReturnType<typeof getPublic>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublic>>> = ({ signal }) => getPublic({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPublicQueryResult = NonNullable<Awaited<ReturnType<typeof getPublic>>>
export type GetPublicQueryError = unknown



export function useGetPublic<TData = Awaited<ReturnType<typeof getPublic>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPublic>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPublicQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export type getPrivateResponse200 = {
  data: void
  status: 200
}

export type getPrivateResponseSuccess = (getPrivateResponse200) & {
  headers: Headers;
};
;

export type getPrivateResponse = (getPrivateResponseSuccess)

export const getGetPrivateUrl = () => {




  return `/api/private`
}

export const getPrivate = async ( options?: RequestInit): Promise<getPrivateResponse> => {

  const res = await fetch(getGetPrivateUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPrivateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getPrivateResponse
}





export const getGetPrivateQueryKey = () => {
    return [
    `/api/private`
    ] as const;
    }


export const getGetPrivateQueryOptions = <TData = Awaited<ReturnType<typeof getPrivate>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrivateQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrivate>>> = ({ signal }) => getPrivate({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPrivateQueryResult = NonNullable<Awaited<ReturnType<typeof getPrivate>>>
export type GetPrivateQueryError = unknown



export function useGetPrivate<TData = Awaited<ReturnType<typeof getPrivate>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPrivate>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPrivateQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}
